package com.zenlayercloud.zlb20250401.models;

import com.aliyun.tea.TeaModel;

import java.util.List;

/**
 * Auto-generated by SDK Generator
 */
public class DescribeLoadBalancersResponse extends TeaModel {


    public String requestId;

    public Integer totalCount;

    public List<LoadBalancer> dataSet;

    public String getRequestId() {
        return this.requestId;
    }

    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    public Integer getTotalCount() {
        return this.totalCount;
    }

    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    public List<LoadBalancer> getDataSet() {
        return this.dataSet;
    }

    public void setDataSet(List<LoadBalancer> dataSet) {
        this.dataSet = dataSet;
    }

}