package com.zenlayercloud.zlb20250401.models;

import com.aliyun.tea.TeaModel;

/**
 * Auto-generated by SDK Generator
 */
public class InquiryPriceCreateLoadBalancerResponse extends TeaModel {

    public String requestId;

    public PriceItem loadBalancerInstancePrice;

    public PriceItem eipPrice;

    public PriceItem eipNetworkPrice;

    public PriceItem lcuPrice;

    public String getRequestId() {
        return this.requestId;
    }

    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    public PriceItem getLoadBalancerInstancePrice() {
        return this.loadBalancerInstancePrice;
    }

    public void setLoadBalancerInstancePrice(PriceItem loadBalancerInstancePrice) {
        this.loadBalancerInstancePrice = loadBalancerInstancePrice;
    }

    public PriceItem getEipPrice() {
        return this.eipPrice;
    }

    public void setEipPrice(PriceItem eipPrice) {
        this.eipPrice = eipPrice;
    }

    public PriceItem getEipNetworkPrice() {
        return this.eipNetworkPrice;
    }

    public void setEipNetworkPrice(PriceItem eipNetworkPrice) {
        this.eipNetworkPrice = eipNetworkPrice;
    }

    public PriceItem getLcuPrice() {
        return this.lcuPrice;
    }

    public void setLcuPrice(PriceItem lcuPrice) {
        this.lcuPrice = lcuPrice;
    }

}