package com.zenlayercloud.zlb20250401.models;

import com.aliyun.tea.TeaModel;

import java.util.List;

/**
 * Auto-generated by SDK Generator
 */
public class PriceItem extends TeaModel {

    public Double discount;

    public Double discountPrice;

    public Double originalPrice;

    public Double unitPrice;

    public Double discountUnitPrice;

    public String chargeUnit;

    public List<StepPrice> stepPrices;

    public String amountUnit;

    public Double excessUnitPrice;

    public Double excessDiscountUnitPrice;

    public String excessAmountUnit;

    public Double getDiscount() {
        return this.discount;
    }

    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    public Double getDiscountPrice() {
        return this.discountPrice;
    }

    public void setDiscountPrice(Double discountPrice) {
        this.discountPrice = discountPrice;
    }

    public Double getOriginalPrice() {
        return this.originalPrice;
    }

    public void setOriginalPrice(Double originalPrice) {
        this.originalPrice = originalPrice;
    }

    public Double getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Double getDiscountUnitPrice() {
        return this.discountUnitPrice;
    }

    public void setDiscountUnitPrice(Double discountUnitPrice) {
        this.discountUnitPrice = discountUnitPrice;
    }

    public String getChargeUnit() {
        return this.chargeUnit;
    }

    public void setChargeUnit(String chargeUnit) {
        this.chargeUnit = chargeUnit;
    }

    public List<StepPrice> getStepPrices() {
        return this.stepPrices;
    }

    public void setStepPrices(List<StepPrice> stepPrices) {
        this.stepPrices = stepPrices;
    }

    public String getAmountUnit() {
        return this.amountUnit;
    }

    public void setAmountUnit(String amountUnit) {
        this.amountUnit = amountUnit;
    }

    public Double getExcessUnitPrice() {
        return this.excessUnitPrice;
    }

    public void setExcessUnitPrice(Double excessUnitPrice) {
        this.excessUnitPrice = excessUnitPrice;
    }

    public Double getExcessDiscountUnitPrice() {
        return this.excessDiscountUnitPrice;
    }

    public void setExcessDiscountUnitPrice(Double excessDiscountUnitPrice) {
        this.excessDiscountUnitPrice = excessDiscountUnitPrice;
    }

    public String getExcessAmountUnit() {
        return this.excessAmountUnit;
    }

    public void setExcessAmountUnit(String excessAmountUnit) {
        this.excessAmountUnit = excessAmountUnit;
    }

}