package com.zenlayercloud.zlb20250401.models;

import com.aliyun.tea.TeaModel;


/**
 * Auto-generated by SDK Generator
 */
public class StepPrice extends TeaModel {


    public Double stepStart;

    public Double stepEnd;

    public Double unitPrice;

    public Double discountUnitPrice;

    public Double getStepStart() {
        return this.stepStart;
    }

    public void setStepStart(Double stepStart) {
        this.stepStart = stepStart;
    }

    public Double getStepEnd() {
        return this.stepEnd;
    }

    public void setStepEnd(Double stepEnd) {
        this.stepEnd = stepEnd;
    }

    public Double getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Double getDiscountUnitPrice() {
        return this.discountUnitPrice;
    }

    public void setDiscountUnitPrice(Double discountUnitPrice) {
        this.discountUnitPrice = discountUnitPrice;
    }

}